### PR TITLE
[add] github actions and some vim version in test

### PR DESCRIPTION
**Pull request by kazukazuinaina**
Hello, cocopon.
Thanks for creating great Vim plugin.
I add github-actions.

- This removes the circleci's dependency.
- Add more vim version in test   e.g: vim8.1, vim8.2...

Could you check this PR?
If you don't need this pull request, feel free to close it.

> https://github.com/thinca/action-setup-vim

### CODE REVIEW

**Comment by kazukazuinaina** [comment]
This CI may run if you merge this patch in master...

**Comment by kazukazuinaina** [comment]
@cocopon 
If you don't need this, feel free to close it.

**Comment by cocopon** [comment]
Great! Sorry for my late reply and thank you for your contribution.

**Comment by kazukazuinaina** [comment]
@cocopon 
Thanks for your review and merge!

**Pull request merged**
